### ISSUE TITLE
Allowed_methods for parameterized urls

### ISSUE THREAD

**Issue by renejahn** [sseemayer/hug_middleware_cors#1]
Hey thanks for providing this middleware!

I have tried to use it in a project and we have a case, which I think is very common and should be covered.

Setting up an endpoint like
`@hug.delete(/users/{user_id}, ... )`

results in a problem, because the middleware will try to match request.path against the route:
* route: `'/user/{user_id}'`
* request.path: `/user/1` (example)

So a parameterized route can not be matched. Any way we can (safely) distinguish a parameter from a regular route?

Another thought: Why not allow users to set allowed_origins when creating the Middleware object?

**Comment by sseemayer** [comment]
Thanks for the great idea! My first idea would be to take advantage of the hug parameter parsing code to try and parse the parameters without launching the route handler. I don't have time to experiment on this right now so it might take a while for me to start working on this. I would be very gladly accepting a PR to this repository, though 👍 

In regards to your second thought: The `allow_origins` parameter should already get passed to the [constructor of the CORSMiddleware](https://github.com/sseemayer/hug_middleware_cors/blob/11e3cc9d5f541d95260aa12e6d57771cac8f9763/hug_middleware_cors.py#L12) so this should already be possible.

**Comment by renejahn** [comment]
Thanks for your answer. I also do not have much time at the moment, but I might have a look later. I think it would be a good idea to have a look at hugs parsing algorithm! 

For the second thought I meant to write `allowed_methods` instead of `allowed_origins` (whoops). That would allow for protecting delete routes more restrictively than others.
Following the default for allowed_origins, which is *, for the methods as default one could define to allow all methods (or maybe better: all that are found to be used in the project, like you intended) but also let the user throw in a specific list of methods to be allowed like just GET and POST.

**Comment by cbrew** [comment]
a simple patch is to retain the existing code to determine allowed_methods, but guard it with try ... except, so that if it fails we get a sensible default value of allowing everything reasonable.

```
try: 
            ...
         response.set_header('Access-Control-Allow-Methods',
                                    ', '.join(allowed_methods))
            except KeyError:
                response.set_header('Access-Control-Allow-Methods',
                                    'GET, PUT, POST, DELETE, HEAD')
```

**Comment by ChiliConSql** [comment]
@sseemayer Thank you for giving us this much needed middleware. I was having the same issues as @renejahn, so I added some code to fix it. Seems to work, so I created a pull request for you.
Let me know what you think.

**Comment by sseemayer** [comment]
Yikes, I seem to have forgotten to close this - doing so now :)
