### ISSUE TITLE
Latest version not in PyPI

### ISSUE THREAD

**Issue by jsangradorp** [sseemayer/hug_middleware_cors#4]
Hi, thanks for making this code available, it has saved me a lot of work.

If you install hug-middleware-cors from PyPI (https://pypi.python.org/pypi/hug-middleware-cors), you don't get the current version, which contains important improvements to the 1.0.0 included there. Would it be possible for you to update PyPI?

Thanks!

**Comment by sseemayer** [comment]
sorry about the late reply! if you haven't seen it yet, hug-middleware-cors is now part of hug itself so there is no need to install from PyPI: https://github.com/timothycrosley/hug/blob/519b956b33b49ee10808fcc5be3238ac78310399/hug/middleware.py#L108
